### ISSUE TITLE
Method call in a class initializer is not implemented

### ISSUE THREAD

**Issue by chitoku-k** [php-java/php-java#139]
# Tell me your versions
- **PHP**
```
PHP 7.3.5 (cli) (built: May  2 2019 12:40:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5, Copyright (c) 1999-2018, by Zend Technologies
```

- **JDK**
```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
```

- **PHPJava**
77668dbc81dc27dd8c195a62c215add82311d60e

# Summary
A method call in a class initializer throws an exception.

# Code
```java
class Cat
{
    protected String comment;
 
    public void meow()
    {
        System.out.println(this.comment);
    }
}

class HelloCat
{
    public static void main(String[] args)
    {
        new Cat() {{
            this.comment = "Hello, I am a cat.";
            meow();
        }};
    }
}
```

Find a reproducible sample here: https://github.com/chitoku-k/php-java-test/commit/8462d5b93f630e991fa673adb452a7698f2875bf

# Expected
```
Hello, I am a cat.
```

# Actual
```
PHP Fatal error:  Uncaught PHPJava\Packages\java\lang\NoSuchMethodException: Call to undefined method meow. in /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Invoker/Invokable.php:369
Stack trace:
#0 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Invoker/Invokable.php(89): PHPJava\Core\JVM\Invoker\DynamicMethodInvoker->findMethod('meow')
#1 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Cache/Cache.php(13): PHPJava\Core\JVM\Invoker\DynamicMethodInvoker->PHPJava\Core\JVM\Invoker\{closure}()
#2 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Invoker/Invokable.php(91): PHPJava\Core\JVM\Cache\Cache->fetchOrPush('meow.', Object(Closure))
#3 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Kernel/Mnemonics/_invokevirtual.php(59): PHPJava\Core\JVM\Invoker\DynamicMethodInvoker->call('meow')
#4 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Invoker/Invokable. in /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Kernel/Mnemonics/_invokespecial.php on line 96
```

**Comment by m3m0r7** [comment]
I'll fix it later. Thanks for your reporting!

**Comment by m3m0r7** [comment]
It seems that it needs to implement `EnclosingMethod` attribute.
(PHPJava has not implemented it yet 😭 )

**Comment by chitoku-k** [comment]
Oh..., is that going to be implemented in the near future?

**Comment by m3m0r7** [comment]
Yes, I'm implementing now.

**Comment by chitoku-k** [comment]
Thanks for quick fix!

I still see the same problem even though I updated php-java to dev-master: https://github.com/chitoku-k/php-java-test/commit/99e7069953eba4439dc0931e87c8ae5360476449. The only difference I so far found is that this test repo builds a JAR file. Hope this helps.

This is the log it fails: https://travis-ci.org/chitoku-k/php-java-test/builds/530838374

**Comment by m3m0r7** [comment]
@chitoku-k 
It seems like PHPJava does not resolve outer class' method between `{{` and `}}`... 😭 
I'll fix it later. Thank you for your reporting!

**Comment by m3m0r7** [comment]
And It seems like this problem appearing `jar` only 🤔

**Comment by m3m0r7** [comment]
Resolved by https://github.com/php-java/php-java/pull/146
