### ISSUE TITLE
Is it compatible with php8 or higher?

### ISSUE THREAD

**Issue by Samuei2000** [php-java/php-java#278]
# Tell me your versions
- **PHP**
PHP 8.3.9 (cli) (built: Jul  2 2024 18:17:57) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.3.9, Copyright (c) Zend Technologies
    with Xdebug v3.3.2, Copyright (c) 2002-2024, by Derick Rethans
- **JDK**
java 17.0.10 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.10+11-LTS-240, mixed mode, sharing)
- **PHPJava**
Console Tool
# Summary
I can't run the quick start.
# Code
```php
<?php
require __DIR__ . '/vendor/autoload.php';
use PHPJava\Core\JavaClass;
use PHPJava\Core\Stream\Reader\FileReader;
 
JavaClass::load('HelloWorld')
    ->getInvoker()
    ->getStatic()
    ->getMethods()
    ->call(
        'main',
        ["Hello World!"]
    );
```
# Expect

# Actual
```
PS D:\php-java> php .\HelloWorld.php
PHP Fatal error:  Uncaught Error: Class "PHPJava\Core\JavaClass" not found in D:\php-java\HelloWorld.php:5
Stack trace:
#0 {main}
  thrown in D:\php-java\HelloWorld.php on line 5

Fatal error: Uncaught Error: Class "PHPJava\Core\JavaClass" not found in D:\php-java\HelloWorld.php on line 5

Error: Class "PHPJava\Core\JavaClass" not found in D:\php-java\HelloWorld.php on line 5

Call Stack:
    0.0003     393320   1. {main}() D:\php-java\HelloWorld.php:0

PS D:\php-java> php .\HelloWorld.php
PHP Deprecated:  Return type of PHPJava\Core\JVM\ConstantPool::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 114
PHP Stack trace:
PHP   1. {main}() D:\php-java\HelloWorld.php:0
PHP   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = *uninitialized*, $enableInstantiated = *uninitialized*) D:\php-java\HelloWorld.php:6
PHP   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
PHP   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
PHP   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
PHP   6. include() D:\php-java\vendor\composer\ClassLoader.php:576

Deprecated: Return type of PHPJava\Core\JVM\ConstantPool::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 114

Call Stack:
    0.0002     393376   1. {main}() D:\php-java\HelloWorld.php:0
    0.0078     587416   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = ???, $enableInstantiated = ???) D:\php-java\HelloWorld.php:6
    0.0143     854592   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
    0.0218    1230416   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
    0.0219    1230528   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
    0.0222    1253448   6. include('D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:576

PHP Deprecated:  Return type of PHPJava\Core\JVM\ConstantPool::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 123
PHP Stack trace:
PHP   1. {main}() D:\php-java\HelloWorld.php:0
PHP   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = *uninitialized*, $enableInstantiated = *uninitialized*) D:\php-java\HelloWorld.php:6
PHP   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
PHP   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
PHP   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
PHP   6. include() D:\php-java\vendor\composer\ClassLoader.php:576

Deprecated: Return type of PHPJava\Core\JVM\ConstantPool::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 123

Call Stack:
    0.0002     393376   1. {main}() D:\php-java\HelloWorld.php:0
    0.0078     587416   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = ???, $enableInstantiated = ???) D:\php-java\HelloWorld.php:6
    0.0143     854592   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
    0.0218    1230416   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
    0.0219    1230528   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
    0.0222    1253448   6. include('D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:576

PHP Deprecated:  Return type of PHPJava\Core\JVM\ConstantPool::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 147
PHP Stack trace:
PHP   1. {main}() D:\php-java\HelloWorld.php:0
PHP   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = *uninitialized*, $enableInstantiated = *uninitialized*) D:\php-java\HelloWorld.php:6
PHP   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
PHP   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
PHP   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
PHP   6. include() D:\php-java\vendor\composer\ClassLoader.php:576

Deprecated: Return type of PHPJava\Core\JVM\ConstantPool::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 147

Call Stack:
    0.0002     393376   1. {main}() D:\php-java\HelloWorld.php:0
    0.0078     587416   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = ???, $enableInstantiated = ???) D:\php-java\HelloWorld.php:6
    0.0143     854592   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
    0.0218    1230416   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
    0.0219    1230528   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
    0.0222    1253448   6. include('D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:576

PHP Deprecated:  Return type of PHPJava\Core\JVM\ConstantPool::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 155
PHP Stack trace:
PHP   1. {main}() D:\php-java\HelloWorld.php:0
PHP   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = *uninitialized*, $enableInstantiated = *uninitialized*) D:\php-java\HelloWorld.php:6
PHP   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
PHP   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
PHP   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
PHP   6. include() D:\php-java\vendor\composer\ClassLoader.php:576

Deprecated: Return type of PHPJava\Core\JVM\ConstantPool::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 155

Call Stack:
    0.0002     393376   1. {main}() D:\php-java\HelloWorld.php:0
    0.0078     587416   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = ???, $enableInstantiated = ???) D:\php-java\HelloWorld.php:6
    0.0143     854592   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
    0.0218    1230416   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
    0.0219    1230528   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
    0.0222    1253448   6. include('D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:576

PHP Deprecated:  Return type of PHPJava\Core\JVM\ConstantPool::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 139
PHP Stack trace:
PHP   1. {main}() D:\php-java\HelloWorld.php:0
PHP   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = *uninitialized*, $enableInstantiated = *uninitialized*) D:\php-java\HelloWorld.php:6
PHP   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
PHP   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
PHP   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
PHP   6. include() D:\php-java\vendor\composer\ClassLoader.php:576

Deprecated: Return type of PHPJava\Core\JVM\ConstantPool::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 139

Call Stack:
    0.0002     393376   1. {main}() D:\php-java\HelloWorld.php:0
    0.0078     587416   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = ???, $enableInstantiated = ???) D:\php-java\HelloWorld.php:6
    0.0143     854592   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
    0.0218    1230416   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
    0.0219    1230528   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
    0.0222    1253448   6. include('D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:576

PHP Deprecated:  Return type of PHPJava\Core\JVM\ConstantPool::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 163
PHP Stack trace:
PHP   1. {main}() D:\php-java\HelloWorld.php:0
PHP   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = *uninitialized*, $enableInstantiated = *uninitialized*) D:\php-java\HelloWorld.php:6
PHP   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
PHP   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
PHP   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
PHP   6. include() D:\php-java\vendor\composer\ClassLoader.php:576

Deprecated: Return type of PHPJava\Core\JVM\ConstantPool::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php on line 163

Call Stack:
    0.0002     393376   1. {main}() D:\php-java\HelloWorld.php:0
    0.0078     587416   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = ???, $enableInstantiated = ???) D:\php-java\HelloWorld.php:6
    0.0143     854592   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 8 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
    0.0218    1230416   4. Composer\Autoload\ClassLoader->loadClass($class = 'PHPJava\\Core\\JVM\\ConstantPool') D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
    0.0219    1230528   5. Composer\Autoload\{closure:D:\php-java\vendor\composer\ClassLoader.php:575-577}($file = 'D:\\php-java\\vendor\\composer/../php-java/php-java/src\\Core\\JVM\\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:427
    0.0222    1253448   6. include('D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php') D:\php-java\vendor\composer\ClassLoader.php:576

PHP Fatal error:  Uncaught Error: Class "String_" not found in D:\php-java\vendor\php-java\php-java\src\Core\JVM\PHPClassInvoker.php:126
Stack trace:
#0 D:\php-java\vendor\php-java\php-java\src\Kernel\Structures\Utf8Info.php(45): PHPJava\Core\JVM\PHPClassInvoker->construct('java/lang/Objec...')
#1 D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php(52): PHPJava\Kernel\Structures\Utf8Info->execute()
#2 D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php(152): PHPJava\Core\JVM\ConstantPool->__construct(Object(PHPJava\Core\Stream\Reader\FileReader), 27)
#3 D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php(142): PHPJava\Core\JavaCompiledClass->__construct(Object(PHPJava\Core\Stream\Reader\FileReader), Array)
#4 D:\php-java\HelloWorld.php(6): PHPJava\Core\JavaClass::load('HelloWorld')
#5 {main}
  thrown in D:\php-java\vendor\php-java\php-java\src\Core\JVM\PHPClassInvoker.php on line 126

Fatal error: Uncaught Error: Class "String_" not found in D:\php-java\vendor\php-java\php-java\src\Core\JVM\PHPClassInvoker.php on line 126

Error: Class "String_" not found in D:\php-java\vendor\php-java\php-java\src\Core\JVM\PHPClassInvoker.php on line 126

Call Stack:
    0.0002     393376   1. {main}() D:\php-java\HelloWorld.php:0
    0.0078     587416   2. PHPJava\Core\JavaClass::load($classPath = 'HelloWorld', $options = ???, $enableInstantiated = ???) D:\php-java\HelloWorld.php:6
    0.0143     854592   3. PHPJava\Core\JavaCompiledClass->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 42 } }, $options = []) D:\php-java\vendor\php-java\php-java\src\Core\JavaClass.php:142
    0.0262    1252768   4. PHPJava\Core\JVM\ConstantPool->__construct($reader = class PHPJava\Core\Stream\Reader\FileReader { private $handle = resource(40) of type (stream); private $binaryReader = class PHPJava\Core\JVM\Stream\BinaryReader { private $handle = resource(40) of type (stream); private $offset = 42 } }, $entries = 27) D:\php-java\vendor\php-java\php-java\src\Core\JavaCompiledClass.php:152
    0.0299    1297120   5. PHPJava\Kernel\Structures\Utf8Info->execute() D:\php-java\vendor\php-java\php-java\src\Core\JVM\ConstantPool.php:52
    0.0401    1562264   6. PHPJava\Core\JVM\PHPClassInvoker->construct(...$arguments = variadic('java/lang/Object')) D:\php-java\vendor\php-java\php-java\src\Kernel\Structures\Utf8Info.php:45
```

# My directory:
"D:\php-java\vendor"
"D:\php-java\composer.json"
"D:\php-java\composer.lock"
"D:\php-java\HelloWorld.class"
"D:\php-java\HelloWorld.java"
"D:\php-java\HelloWorld.php"

**Comment by m3m0r7** [comment]
Windows is not supported officially. and the repository is no longer maintained.
But it seems to invalid autoloading path in your composer.

Try to run:

```
$ git clone https://github.com/php-java/php-java.git
$ cd php-java
$ composer install
$ ./vendor/bin/phpunit tests/Cases
```

or welcome to fix this issue yourself.
